// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// charlieplexing6 //
// --------------- //

#define charlieplexing6_wrap_target 0
#define charlieplexing6_wrap 10

static const uint16_t charlieplexing6_program_instructions[] = {
            //     .wrap_target
    0x8080, //  0: pull   noblock                    
    0xa027, //  1: mov    x, osr                     
    0x6083, //  2: out    pindirs, 3                 
    0x7f03, //  3: out    pins, 3                [31]
    0xff5f, //  4: set    y, 31                  [31]
    0x1f85, //  5: jmp    y--, 5                 [31]
    0x7f03, //  6: out    pins, 3                [31]
    0xff5f, //  7: set    y, 31                  [31]
    0x1f88, //  8: jmp    y--, 8                 [31]
    0xe000, //  9: set    pins, 0                    
    0x00e2, // 10: jmp    !osre, 2                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program charlieplexing6_program = {
    .instructions = charlieplexing6_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config charlieplexing6_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + charlieplexing6_wrap_target, offset + charlieplexing6_wrap);
    return c;
}
#endif

